name: CI

on: issues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: brcrista/summarize-issues@dev
      with:
        title: 'My Issues Report'
        outputPath: 'IssuesReport.md'
        configPath: '.github/workflows/issues-report-config.json'
